export default {
        login: "joyce0011",
        id: 61491800,
        node_id: "MDQ6VXNlcjYxNDkxODAw",
        avatar_url: "https://avatars.githubusercontent.com/u/61491800?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/joyce0011",
        html_url: "https://github.com/joyce0011",
        followers_url: "https://api.github.com/users/joyce0011/followers",
        following_url: "https://api.github.com/users/joyce0011/following{/other_user}",
        gists_url: "https://api.github.com/users/joyce0011/gists{/gist_id}",
        starred_url: "https://api.github.com/users/joyce0011/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/joyce0011/subscriptions",
        organizations_url: "https://api.github.com/users/joyce0011/orgs",
        repos_url: "https://api.github.com/users/joyce0011/repos",
        events_url: "https://api.github.com/users/joyce0011/events{/privacy}",
        received_events_url: "https://api.github.com/users/joyce0011/received_events",
        type: "User",
        site_admin: false,
        name: "joyce",
        company: "me",
        blog: "https://joyce0011.github.io/archives/",
        location: "Shanghai，China",
        email: null,
        hireable: null,
        bio: " like JavaScript ,react 🔥",
        twitter_username: null,
        public_repos: 9,
        public_gists: 0,
        followers: 1,
        following: 2,
        created_at: "2020-02-26T06:56:25Z",
        updated_at: "2023-03-24T06:37:46Z"
};
